llm:
  api_type: "openai"
  model: "gemini-3-flash-preview"
  base_url: "https://newapi.deepwisdom.ai/v1"
  api_key: sk-fqEL7wgzCbUxrSJNVpOjs280XMosctAHp5I5xcIV8NXOConv

case_generator:
  api_type: "openai"
  model: "gpt-4o"
  base_url: "https://newapi.deepwisdom.ai/v1"
  api_key: "sk-fqEL7wgzCbUxrSJNVpOjs280XMosctAHp5I5xcIV8NXOConv"